esphome:
  name: reader-test
  friendly_name: Reader Test
  platformio_options:
    build_flags: 
      - -DARDUINO_USB_CDC_ON_BOOT=0
      - -DARDUINO_USB_MSC_ON_BOOT=0
      - -DARDUINO_USB_DFU_ON_BOOT=0
      - -DBOARD_HAS_PSRAM
    board_build.arduino.memory_type: qio_opi
    board_build.flash_mode: dio

esp32:
  board: esp32-s3-devkitc-1
  variant: esp32s3
  framework:
    type: arduino
  flash_size: 16MB

psram:
  mode: octal
  speed: 40MHz

# Enable Web Server for browser access
web_server:
  port: 80

# Enable mDNS for discovery
mdns:
  disabled: false

spi:
  clk_pin: 12
  mosi_pin: 11
  miso_pin: 13

pn532_spi:
  cs_pin: 10
  update_interval: 1s
  on_tag:
    then:
      - homeassistant.tag_scanned: !lambda 'return x;'
      - logger.log:
          format: "Found tag with UID: %s"
          args: [ 'x.c_str()' ]
      - light.turn_on:
          id: onboard_led
          brightness: 50%
          red: 0%
          green: 100%
          blue: 0%
      - delay: 3s
      - light.turn_off: onboard_led

light:
  - platform: esp32_rmt_led_strip
    id: onboard_led
    name: "Onboard LED"
    pin: 48
    num_leds: 1
    rgb_order: GRB
    chipset: SK6812

binary_sensor:
  - platform: pn532
    uid: 04-92-A2-A2-4D-60-80 # Example UID, replace with your actual tag UID if needed
    name: "PN532 Tag"

logger:
  hardware_uart: UART0
  level: DEBUG
  baud_rate: 115200

api:
ota:
  - platform: esphome

wifi:
  ssid: "Home"
  password: "Kayden2016"
  ap:
    ssid: "Reader-Test-Fallback"

captive_portal:
